config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticate :user do
    resources :institutions
    resources :patients
    resources :institutions
    resources :user_institutions
  end
  resources :user_institutions do
    resources :inscriptions
    resources :patients
  end

  resources :inscriptions do
    resources :diagnostics
    resources :traces
    resources :inscription_files
  end

  resources :patients do
    resources :diagnostics
    resources :traces
  end

  resources :diagnostics, only: [:edit, :destroy]
  resources :traces, only: [:edit, :destroy]
  

 root 'user_institutions#index'

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :user_institutions
  has_many :users, through: :user_institutions
  
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /institutions
  # GET /institutions.json
  def index
    @user = current_user
    @institutions = @user.institutions
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institutions = Institution.all
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)
    @institution.users << current_user
    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_for @institution, :html => { :class => "form-horizontal institution" } do |f| %>

    <% if @institution.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @institution.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>



    <div class="form-group">
      <%= f.label :name, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%= error_span(@institution[:name]) %>
    </div>
    <br>
    <br>
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            institutions_path, :class => 'btn btn-default' %>

<% end %>

app/views/institutions/edit.html.erb
<%- model_class = Institution -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/institutions/index.html.erb
<%- model_class = Institution -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%=  link_to institution.name, institution_path(institution), class:"btn btn-default btn-block" %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_institution_path(institution), :class => 'btn btn-default ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      institution_path(institution),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_institution_path,
            :class => 'btn btn-primary' %>

app/views/institutions/new.html.erb
<%- model_class = Institution -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="container ">
<div class="row">
  <%= render :partial => 'form' %>
</div>

app/views/institutions/show.html.erb
<%- model_class = Institution -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @institution.name %></dd>
  <dt><strong>Patients:</strong></dt>
  <dd><table class="table table-striped">
   <thead>
     <tr>
       <th>First Name</th>
       <th>Last Name</th>
       <th>Action</th>
     </tr>
   </thead>
   <tbody>
     <%@institution.patients.each do |patient|%>
        <tr>
          <td><%= patient.first_name%></td>
          <td><%= patient.last_name %></td>
          <td><%= link_to "View",patient_path(patient), class:"btn btn-primary"%></td>
        </tr>
     <%end%>
   </tbody>
 </table>
 <%= link_to "New Patient", new_institution_patient_path(@institution), class: "btn btn-default"%></dd>
</dl>


<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              institutions_path, :class => 'btn btn-default'  %>