config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticate :user do
    resources :institutions
    resources :patients
    resources :institutions
    resources :user_institutions
  end
  resources :user_institutions do
    resources :inscriptions
    resources :patients
  end

  resources :inscriptions do
    resources :diagnostics
    resources :traces
    resources :inscription_files
  end

  resources :patients do
    resources :diagnostics
    resources :traces
  end

  resources :diagnostics, only: [:edit, :destroy]
  resources :traces, only: [:edit, :destroy]
  

 root 'user_institutions#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :inscriptions
  has_many :user_institutions, through: :inscriptions

  validates :identification_document, uniqueness: true
  
  def age
    if (birthdate != nil) then
      now = Time.now.utc
      now.year - birthdate.year - (birthdate.to_time.change(:year => now.year) > now ? 1 : 0)
    else
      nil
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /patients
  # GET /patients.json
  def index
    @user = current_user
    if (params.include?(:user_institution_id))
      @user_institution = UserInstitution.find(params[:user_institution_id])
      @patients = @user_institution.patients.order("last_name ASC")
    else
      @patients = Patient.all.order("last_name ASC")
      render :index_all
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    session[:patient_id] = @patient.id
    if (params.include?(:user_institution_id))
      @user_institution = UserInstitution.find(params[:user_institution_id])
      @inscription = @patient.inscriptions.find_by_user_institution_id(@user_institution.id)
      @diagnostics = @patient.inscriptions.find_by_user_institution_id(@user_institution.id).diagnostics
      @traces = @patient.inscriptions.find_by_user_institution_id(@user_institution.id).traces
      @files = @patient.inscriptions.find_by_user_institution_id(@user_institution.id).inscription_files
    else
      @patient = Patient.find(params[:id])
      render :showAll
    end
  end

  # GET /patients/new
  def new
    @patients = Patient.all
    @patient = Patient.new
    @user_institution = UserInstitution.find(params[:user_institution_id])
  end

  # GET /patients/1/edit
  def edit
    if (params.include?(:user_institution_id))
      @user_institution = UserInstitution.find(params[:user_institution_id])
    else
      render :editAll
    end
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @user_institution = UserInstitution.find(params[:user_institution_id])
    if @patient.valid? then
      @user_institution.patients << @patient
    end
    respond_to do |format|
      if @patient.save && @user_institution.save then
        format.html { redirect_to user_institution_patients_path(@user_institution), notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    if params.include?(:user_institution_id) then
      @user_institution = UserInstitution.find(params[:user_institution_id])
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to user_institution_patient_path(@user_institution,@patient), notice: 'Patient was successfully updated.' }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to patient_path(@patient), notice: 'Patient was successfully updated.'}
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :birthdate, :identification_document, :marital_status, :addres, :personal_phone, :cell_phone, :occupation, :os_name, :os_identification, :past, :past_family, :toxic_abit, :others, :childrens)
    end

    def diagnostic_params
      params.require(:patient).permit(diagnostics_attributes: [:visit, :description, :medicament])
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for [@user_institution,@patient], :html => { :class => "form-horizontal patient" } do |f| %>

    <% if @patient.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
    <%= error_span(@patient[:first_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%= error_span(@patient[:last_name]) %>
    <div class="control-group">
      <%= f.label :birthdate, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_field :birthdate, :class => 'form-control' %>
     </div>
    </div>
    <div class="control-group">
      <%= f.label :identification_document, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :identification_document, :class => 'form-control' %>
     </div>
    </div>
    <div class="control-group">
      <%= f.label :marital_status, :class => 'control-label' %>
      <div class="controls ">
        <%= f.select :marital_status  do %>
          <% [["Casado/a","Casado/a"],["Soltero/a","Soltero/a"],["Divorciado/a","Divorciado/a"],["Conviviente","Conviviente"]].each  do |item|%>
              <%= content_tag(:option,item.first, value: item.last)%>
          <%end%>
        <%end%>
     </div>
     <div class="control-group">
       <%= f.label :sex, :class => 'control-label' %>
       <div class="controls ">
         <%= f.select :sex do %>
           <% [["Masculino","Masculino"],["Femenino","Femenino"]].each  do |item|%>
               <%= content_tag(:option,item.first, value: item.last)%>
           <%end%>
         <%end%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :childrens, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :childrens,in: 0..100,step:1, class:"form-control" %>
     </div>
   </div>
   <div class="control-group">
     <%= f.label :addres, :class => 'control-label' %>
     <div class="controls">
       <%= f.text_field :addres, class:"form-control" %>
    </div>
    <div class="control-group">
      <%= f.label :city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :city, class:"form-control" %>
     </div>
    <div class="control-group">
      <%= f.label :location, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :location, class:"form-control" %>
     </div>
     <div class="control-group">
       <%= f.label :postal_code, :class => 'control-label' %>
       <div class="controls">
         <%= f.text_field :postal_code, class:"form-control" %>
      </div>
  </div>
  <div class="control-group">
    <%= f.label :personal_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.telephone_field :personal_phone, class:"form-control" %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :cell_phone, :class => 'control-label' %>
   <div class="controls">
     <%= f.telephone_field :cell_phone, class:"form-control" %>
  </div>
</div>
<div class="control-group">
  <%= f.label :occupation, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :occupation, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :os_name, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :os_name, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :os_identification, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :os_identification, class:"form-control", rows:10 %>
 </div>
</div>
<div class="control-group">
  <%= f.label :past, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :past, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :past_family, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :past_family, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :toxic_abit, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :toxic_abit, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :others, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :others, class:"form-control" %>
 </div>
</div>
  <%= button_tag(type: "submit", class: "btn btn-primary") do %>
    <i class="fa fa-check"></i>
  <% end %>
  <%if !params.include?(:id) then %>
    <%= link_to  user_institution_patients_path(@user_institution), :class => 'btn btn-default' do  %>
      <i class="fa fa-ban"></i>
    <%end%>
  <%else%>
    <%= link_to  user_institution_patient_path(@user_institution,@patient), :class => 'btn btn-default' do  %>
      <i class="fa fa-ban"></i>
    <%end%>
  <%end%>

<% end %>

app/views/patients/_formAll.html.erb
<%= form_for @patient, :html => { :class => "form-horizontal patient" } do |f| %>

    <% if @patient.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
    <%= error_span(@patient[:first_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%= error_span(@patient[:last_name]) %>
    <div class="control-group">
      <%= f.label :birthdate, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_field :birthdate, :class => 'form-control' %>
     </div>
    </div>
    <div class="control-group">
      <%= f.label :identification_document, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :identification_document, :class => 'form-control' %>
     </div>
    </div>
    <div class="control-group">
      <%= f.label :marital_status, :class => 'control-label' %>
      <div class="controls ">
        <%= f.select :marital_status do %>
          <% [["Casado","Casado"],["Soltero","Soltero"],["Divorciado","Divorciado"],["Conviviente","Conviviente"]].each  do |item|%>
              <%= content_tag(:option,item.first, value: item.last)%>
          <%end%>
        <%end%>
     </div>
     <div class="control-group">
       <%= f.label :sex, :class => 'control-label' %>
       <div class="controls ">
         <%= f.select :sex do %>
           <% [["Masculino","Masculino"],["Femenino","Femenino"]].each  do |item|%>
               <%= content_tag(:option,item.first, value: item.last)%>
           <%end%>
         <%end%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :childrens, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :childrens,in: 0..100,step:1, class:"form-control" %>
     </div>
   </div>
   <div class="control-group">
     <%= f.label :addres, :class => 'control-label' %>
     <div class="controls">
       <%= f.text_field :addres, class:"form-control" %>
    </div>
    <div class="control-group">
      <%= f.label :city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :city, class:"form-control" %>
     </div>
    <div class="control-group">
      <%= f.label :location, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :location, class:"form-control" %>
     </div>
     <div class="control-group">
       <%= f.label :postal_code, :class => 'control-label' %>
       <div class="controls">
         <%= f.text_field :postal_code, class:"form-control" %>
      </div>
  </div>
  <div class="control-group">
    <%= f.label :personal_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.telephone_field :personal_phone, class:"form-control" %>
   </div>
 </div>
 <div class="control-group">
   <%= f.label :cell_phone, :class => 'control-label' %>
   <div class="controls">
     <%= f.telephone_field :cell_phone, class:"form-control" %>
  </div>
</div>
<div class="control-group">
  <%= f.label :occupation, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :occupation, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :os_name, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :os_name, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :os_identification, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :os_identification, class:"form-control", rows:10 %>
 </div>
</div>
<div class="control-group">
  <%= f.label :past, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :past, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :past_family, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :past_family, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :toxic_abit, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :toxic_abit, class:"form-control" %>
 </div>
</div>
<div class="control-group">
  <%= f.label :others, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :others, class:"form-control" %>
 </div>
</div>
  <%= button_tag(type: "submit", class: "btn btn-primary") do %>
    <i class="fa fa-check"></i>
  <% end %>
  <%= link_to  patient_path(@patient), class:"btn btn-default" do %>
    <i class="fa fa-ban"></i>
  <%end%>

<% end %>

app/views/patients/edit.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/patients/index.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1 class="text-center">Patients <small>already associated with your institution</small></h1>
</div>
<div class="row">
<ul class="list-group col-md-4 col-md-offset-4">
  <% @patients.each do |patient| %>
      <% if (patient.last_name?) then %>
        <%= link_to patient.last_name  + ", " + patient.first_name    , user_institution_patient_path(@user_institution,patient), class:"list-group-item text-center"  %>
      <% else %>
        <%= link_to  patient.first_name    , user_institution_patient_path(@user_institution,patient), class:"list-group-item text-center"  %>
      <%end%>
  <% end %>
</ul>
</div>
<%= link_to  user_institutions_path, class:"btn btn-default" do %>
  <i class="fa fa-chevron-left"></i>
<%end%>
<% if (params.include?("user_institution_id")) then %>
  <%= link_to  new_user_institution_inscription_path(@user_institution), :class => 'btn btn-primary' do %>
    <i class="fa fa-plus"></i>
  <%end%>
<%else%>
  <%= link_to new_user_institution_patient_path, :class => 'btn btn-primary' do  %>
    <i class="fa fa-plus"></i>
  <%end%>
<%end%>

app/views/patients/show.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <%if (@patient.last_name?)%>
    <h1 class="text-center"><%= @patient.last_name + " " + @patient.first_name + " "%><small>deatils</small></h1>
  <%else%>
    <h1 class="text-center"><%=  @patient.first_name + " "%><small>deatils</small></h1>
  <%end%>
</div>
<div class="panel panel-primary"  >
    <div class="panel-heading" ><a role="button" data-toggle="collapse" href="#panel-details">Patient's details </a><%= link_to  edit_user_institution_patient_path(@user_institution,@patient), :class => 'btn-sm btn-default' do %>
                                                  <i class="fa fa-pencil-square-o"></i> <%end%></div>
    <div class="panel-body collapse" id="panel-details">
      <div class="col-md-6">
        <dl class="dl-horizontal">
          <dt><strong>First Name:</strong></dt>
          <dd><%= @patient.first_name %></dd>
          <dt><strong>Last Name:</strong></dt>
          <dd><%= @patient.last_name %></dd>
          <dt><strong>Birthdate:</strong></dt>
          <dd><%= @patient.birthdate %></dd>
          <dt><strong>Age:</strong></dt>
          <dd><%= @patient.age %></dd>
          <dt><strong>Identification Document:</strong></dt>
          <dd><%= @patient.identification_document %></dd>
          <dt><strong>Sex:</strong></dt>
          <dd><%= @patient.sex %></dd>
          <dt><strong>Email:</strong></dt>
          <dd><%= @patient.email %></dd>
          <dt><strong>Marital Status:</strong></dt>
          <dd><%= @patient.marital_status %></dd>
          <dt><strong>Address:</strong></dt>
          <dd><%= @patient.addres %></dd>
          <dt><strong>City:</strong></dt>
          <dd><%= @patient.city %></dd>
          <dt><strong>Location:</strong></dt>
          <dd><%= @patient.location %></dd>
          <dt><strong>Postal Code::</strong></dt>
          <dd><%= @patient.postal_code %></dd>
        </dl>
      </div>
      <div class="col-md-6">
        <dl class="dl-horizontal">
          <dt><strong>Personal Phone:</strong></dt>
          <dd><%= @patient.personal_phone %></dd>
          <dt><strong>Cell Phone:</strong></dt>
          <dd><%= @patient.cell_phone %></dd>
          <dt><strong>Occupation:</strong></dt>
          <dd><%= @patient.occupation %></dd>
          <dt><strong>OS:</strong></dt>
          <dd><%= @patient.os_name %></dd>
          <dt><strong>OS Identification:</strong></dt>
          <dd><%= @patient.os_identification %></dd>
          <dt><strong>Past:</strong></dt>
          <dd><%= @patient.past %></dd>
          <dt><strong>Family Past:</strong></dt>
          <dd><%= @patient.past_family %></dd>
          <dt><strong>Toxic Abits:</strong></dt>
          <dd><%= @patient.toxic_abit %></dd>
          <dt><strong>Others:</strong></dt>
          <dd><%= @patient.others %></dd>
        </dl>
      </div>

    </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading"><a role="button" data-toggle="collapse" href="#panel-files">Files</a><%= link_to  new_inscription_inscription_file_path(@inscription), class: "btn-sm btn-default" do %>
                                                <i class="fa fa-plus"></i>
                                              <%end%></div>
  <div class="panel-body collapse" id="panel-files">
      <div class="table-responsive">
          <table class="table table-stripped" >
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>link</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <%@files.each do |inscriptionFile|%>
                <tr>
                    <td><%= inscriptionFile.name %></td>
                    <td><%= inscriptionFile.description%></td>
                    <td><%= link_to "Link", inscriptionFile.link, target:"_blank" %></td>
                    <td id="actions"><%= link_to edit_inscription_inscription_file_path(@inscription,inscriptionFile), class:"btn-sm btn-default" do%>
                              <i class="fa fa-pencil-square-o"></i>
                         <%end%>
                       <%= link_to  inscription_inscription_file_path(@inscription,inscriptionFile),
                                                 :method => :delete,
                                                 :data => {:confirm => "Are you sure ?"},
                                                 :class => "btn-sm btn-danger" do %>
                           <i class="fa fa-minus"></i>
                       <%end%></td>
                </tr>
              <%end%>
            </tbody>
          </table>
      </div>
  </div>
</div>


<div class="panel panel-primary">
  <div class="panel-heading"><a role="button" data-toggle="collapse" href="#panel-hc">Clinical History </a><%= link_to  new_inscription_diagnostic_path(@inscription), class: "btn-sm btn-default" do %>
                                                <i class="fa fa-plus"></i>
                                              <%end%></div>
  <div class="panel-body" id="panel-hc">
      <div class="table-responsive">
          <table class="table table-stripped" >
            <thead>
              <tr>
                <th>Visit</th>
                <th>Description</th>
                <th>Medicaments</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <%@diagnostics.each do |diagnostic|%>
                <tr>
                    <td><%= diagnostic.visit %></td>
                    <td><%= diagnostic.description%></td>
                    <td><%= diagnostic.medicament %></td>
                    <td id="actions"><%= link_to edit_diagnostic_path(diagnostic), class:"btn-sm btn-default" do%>
                              <i class="fa fa-pencil-square-o"></i>
                         <%end%>
                       <%= link_to  diagnostic_path(diagnostic),
                                                 :method => :delete,
                                                 :data => {:confirm => "Are you sure ?"},
                                                 :class => "btn-sm btn-danger" do %>
                           <i class="fa fa-minus"></i>
                       <%end%></td>
                </tr>
              <%end%>
            </tbody>
          </table>
      </div>
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading"><a role="button" data-toggle="collapse" href="#panel-traces">Traces </a><%= link_to  new_inscription_trace_path(@inscription), class: "btn-sm btn-default" do %>
                                      <i class="fa fa-plus"></i>
                                      <%end%></div>
  <div class="panel-body collapse" id="panel-traces">
    <table class="table table-stripped">
      <%  if (@traces.first != nil) then %>
      <% date = @traces.first.created_at.in_time_zone("America/Argentina/Buenos_Aires").to_date  %>
         <thead>
          <th class="info" colspan="3" style="text-align:center" ><%= date.strftime("%d/%m/%Y") %></th>
         </thead>
         <% @traces.each do |trace| %>
           <% if (trace.created_at.in_time_zone("America/Argentina/Buenos_Aires").to_date > date) then %>
             <% date = trace.created_at.in_time_zone("America/Argentina/Buenos_Aires").to_date %>
             <thead>
               <th class = "info" colspan="3" style="text-align:center"><%= date.strftime("%d/%m/%Y") %></th>
             </thead>
             <tbody>
                <td><%= trace.created_at.in_time_zone("America/Argentina/Buenos_Aires").strftime('%T') %></td>
                <td><%= trace.description %></td>
                <td id="actions"><%= link_to edit_trace_path(trace), class:"btn-sm btn-default" do%>
                          <i class="fa fa-pencil-square-o"></i>
                     <%end%>
                   <%= link_to  trace_path(trace),
                                             :method => :delete,
                                             :data => {:confirm => "Are you sure ?"},
                                             :class => "btn-sm btn-danger" do %>
                       <i class="fa fa-minus"></i>
                   <%end%></td>
             </tbody>
           <% else %>
             <tbody>
                <td><%= trace.created_at.in_time_zone("America/Argentina/Buenos_Aires").strftime('%T') %></td>
                <td><%= trace.description %></td>
                <td><%= link_to edit_trace_path(trace), class:"btn-sm btn-default" do%>
                          <i class="fa fa-pencil-square-o"></i>
                     <%end%>
                   <%= link_to  trace_path(trace),
                                             :method => :delete,
                                             :data => {:confirm => "Are you sure ?"},
                                             :class => "btn-sm btn-danger" do %>
                       <i class="fa fa-minus"></i>
                   <%end%></td>
             </tbody>
           <% end %>
         <% end %>
      <%end%>
    </table>
  </div>
</div>



<br>
<br>
<%= link_to user_institution_patients_path(@user_institution), :class => 'btn btn-default'  do %>
  <i class="fa fa-chevron-left"></i>
<%end%>

app/views/patients/showAll.html.erb
<div class="page-header">
  <% if @patient.last_name? %>
    <h1><%= @patient.last_name + " " + @patient.first_name %></h1>
  <%else%>
    <h1><%= @patient.first_name %></h1>
  <%end%>
  <h1></h1>
</div>
</div>
<div class="row">
  <dl class="dl-horizontal">
    <dt><strong>First Name:</strong></dt>
    <dd><%= @patient.first_name %></dd>
    <dt><strong>Last Name:</strong></dt>
    <dd><%= @patient.last_name %></dd>
    <dt><strong>Birthdate:</strong></dt>
    <dd><%= @patient.birthdate %></dd>
    <dt><strong>Age:</strong></dt>
    <dd><%= @patient.age %></dd>
    <dt><strong>Identification Document:</strong></dt>
    <dd><%= @patient.identification_document %></dd>
    <dt><strong>Sex:</strong></dt>
    <dd><%= @patient.sex %></dd>
    <dt><strong>Email:</strong></dt>
    <dd><%= @patient.email %></dd>
    <dt><strong>Marital Status:</strong></dt>
    <dd><%= @patient.marital_status %></dd>
    <dt><strong>Address:</strong></dt>
    <dd><%= @patient.addres %></dd>
    <dt><strong>City:</strong></dt>
    <dd><%= @patient.city %></dd>
    <dt><strong>Location:</strong></dt>
    <dd><%= @patient.location %></dd>
    <dt><strong>Postal Code::</strong></dt>
    <dd><%= @patient.postal_code %></dd>
    <dt><strong>Personal Phone:</strong></dt>
    <dd><%= @patient.personal_phone %></dd>
    <dt><strong>Cell Phone:</strong></dt>
    <dd><%= @patient.cell_phone %></dd>
    <dt><strong>Occupation:</strong></dt>
    <dd><%= @patient.occupation %></dd>
    <dt><strong>OS:</strong></dt>
    <dd><%= @patient.os_name %></dd>
    <dt><strong>OS Identification:</strong></dt>
    <dd><%= @patient.os_identification %></dd>
    <dt><strong>Past:</strong></dt>
    <dd><%= @patient.past %></dd>
    <dt><strong>Family Past:</strong></dt>
    <dd><%= @patient.past_family %></dd>
    <dt><strong>Toxic Abits:</strong></dt>
    <dd><%= @patient.toxic_abit %></dd>
    <dt><strong>Others:</strong></dt>
    <dd><%= @patient.others %></dd>
  </dl>
</div>
<%= link_to  patients_path, class:"btn btn-default" do %>
  <i class="fa fa-arrow-left"></i>
<%end%>
<%= link_to  edit_patient_path(@patient), class:"btn btn-primary" do %>
  <i class="fa fa-pencil-square-o"></i>
<%end%>