config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticate :user do
    resources :institutions
    resources :patients
    resources :institutions
    resources :user_institutions
  end
  resources :user_institutions do
    resources :inscriptions
    resources :patients
  end

  resources :inscriptions do
    resources :diagnostics
    resources :traces
    resources :inscription_files
  end

  resources :patients do
    resources :diagnostics
    resources :traces
  end

  resources :diagnostics, only: [:edit, :destroy]
  resources :traces, only: [:edit, :destroy]
  

 root 'user_institutions#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_institutions
  has_many :institutions, through: :user_institutions
end

app/models/user_institution.rb
class UserInstitution < ActiveRecord::Base
  belongs_to :institution
  belongs_to :user

  has_many :inscriptions
  has_many :patients, through: :inscriptions

  def can_delete
    if !patients.any? then
      true
    else
      false
    end
  end

end

app/controllers/user_institutions_controller.rb
class UserInstitutionsController <ApplicationController
    before_action :authenticate_user!
  def index
    @user = current_user
    @list = UserInstitution.includes(:institution).where("user_institutions.user_id = ?", current_user.id).order("institutions.name ASC")
    @one_can_delete = one_can_delete(@list)
  end

  def new
    @user = current_user
    @list = UserInstitution.includes(:institution).where("user_institutions.user_id = ?", current_user.id)
    @user_institution = UserInstitution.new
    @institutions = Institution.all
  end

  def destroy
    @user_institution = UserInstitution.find(params[:id])
    if !@user_institution.patients.any? then
      @user_institution.destroy
      message = "Institution was succesfully destroyed"
    else
      message = "Can't destroy because that Institution have patients"
    end
    respond_to do |format|
      format.html {redirect_to user_institutions_path, notice: message}
    end
  end

  def create
    @user = current_user
    if (@user.institution_ids.any?) then
      params[:user][:institution_ids].each do |item |
        @user.institution_ids = @user.institution_ids << item
      end
    else
      @user.institution_ids =  params[:user][:institution_ids]
    end
    if @user.save then
      respond_to do |format|
        format.html {redirect_to user_institutions_path, notice: "Succesfully asociated"}
      end
    end
  end

  private

  def one_can_delete(list)
    list.each do |item|
      if (item.can_delete) then
        logger.debug "Entro con item: " + item.id.to_s
        return true
      end
    end
    return false
  end

end

app/views/user_institutions/_form.html.erb
<%= form_for [@user_institution], :html => {:class => "form-horizontal"} do |f| %>


    <h2>Available Institutions</h2>

        <% Institution.all.each do |institution|%>

            <% if !@user.institutions.include?(institution) then %>
              <div class="checkbox">
                  <label>
                    <%= check_box_tag "user[institution_ids][]", institution.id,@user.institutions.include?(institution),id: dom_id(institution)%>
                    <%= institution.name %>
                  </label>
              </div>
            <%end%>
        <%end%>


  <br>
  <%= button_tag(type: "submit", class: "btn btn-primary") do %>
    <i class="fa fa-check"></i>
  <% end %>
  <%= link_to  user_institutions_path, class:"btn btn-default" do  %>
    <i class="fa fa-ban"></i>
  <%end%>
<%end%>

app/views/user_institutions/index.html.erb
<div class ="container">
  <div class = "row">
    <div class="col-md-7">
    <table class="table">
      <thead>
        <tr>
          <th>Institution Name </th>
          <%if @one_can_delete%>
          <th>Actions</th>
          <%end%>
        </tr>
      </thead>
      <tbody>
        <% @list.each do |user_institution|%>
          <tr>
            <td><%= link_to user_institution.institution.name, user_institution_patients_path(user_institution), class:"btn btn-default btn-block" %></td>
            <%if (user_institution.can_delete)%>
            <td><%= link_to  user_institution_path(user_institution.id),
                                      :method => :delete,
                                      :data => {:confirm => "Are you sure ?"},
                                      :class => "btn btn-danger" do %>
                <i class="fa fa-minus"></i>  
            <%end%></td>
           <%end%>
          </tr>
        <%end%>
     </tbody>
   </table>
   <%= link_to new_user_institution_path(@user), class:"btn btn-primary" do %>
   <i class="fa fa-plus"></i>
   <%end%>
 </div>
 </div>
</div>

app/views/user_institutions/new.html.erb
<div class="container">
  <%= render :partial => 'form'%>
</div>